---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
spec:
  selector:
    matchLabels:
      app: dvwa
  replicas: 1
  template:
    metadata:
      labels:
        app: dvwa
        owner: amits
        environment: demo
    spec:
      containers:
      - name: dvwa
        image: howiehowerton/dvwa-howie:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-svc
  labels:
    app: dvwa
    owner: amits
    environment: demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80  
  selector:
    app: dvwa
...